[package]
name = "smart-id-rust-client"
version = "0.1.0"
description = "Smart ID Rust Client"
authors = ["Michallis Pashidis"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = {  version = "0.3.18", features = [
    "env-filter",
    "fmt",
    "json",
] }


[dev-dependencies]
serial_test = { version = "2.0.0", features = ["async"] }
serial_test_derive = "2.0.0"
tracing-test = "0.2.4"

[profile.dev]
opt-level = 1              # Use slightly better optimizations.
strip = false              # Automatically strip symbols from the binary.
split-debuginfo = "packed" # this feature on the dev profile is necessary to make sure we can use GDB for debugging --> will make sure it can load all symbols

[profile.release]
opt-level = "s"
strip = true
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true        # Enables link to optimizations
panic = 'abort'
