[env]
RUST_LOG = "debug"

HOST_URL = "https://sid.demo.sk.ee/smart-id-rp/v2"
RELYING_PARTY_UUID = "00000000-0000-0000-0000-000000000000"
RELYING_PARTY_NAME = "DEMO"
DOCUMENT_NUMBER = "PNOLT-30303039914-MOCK-Q"
DATA_TO_SIGN = "Well hello there!"
CERTIFICATE_LEVEL_QUALIFIED = "QUALIFIED"
CERTIFICATE_LEVEL_ADVANCED = "ADVANCED"
