[env]
RUST_LOG = "hyper=none,smart_id_rust_client=debug,smart_id_client=debug"

SMART_ID_ROOT_URL = "https://sid.demo.sk.ee"
SMART_ID_V3_API_PATH = "/smart-id-rp/v3"
SMART_ID_SCHEME_NAME = "smart-id-demo"
RELYING_PARTY_UUID = "00000000-0000-0000-0000-000000000000"
RELYING_PARTY_NAME = "DEMO"
CLIENT_REQ_NETWORK_TIMEOUT_MILLIS= "30000"

